### ISSUE TITLE
Create userAPI SDK in frontend

### ISSUE THREAD

**Issue by TomChv** [Cleopha/ifttt-like#32]
The frontend will communicate with the userAPI to mange his account, setup workflow and task.

UserAPI is the entrypoint to the backend and the only API exposed.
It's primordial to create a complete SDK in the frontend.

**Comment by TomChv** [comment]
@Thytu What's the current status? Should we close this?

**Comment by Thytu** [comment]
@TomChv closed, it's already merged.
